-- Features 8-12: global Bitcoin public-address research index and workspace metadata

create table if not exists public.btc_address_index (
  address text primary key,
  address_type text,
  first_seen timestamptz,
  last_activity timestamptz,
  balance_sats numeric(30,0) not null default 0 check (balance_sats >= 0),
  funded_sats numeric(30,0) not null default 0 check (funded_sats >= 0),
  spent_sats numeric(30,0) not null default 0 check (spent_sats >= 0),
  tx_count bigint not null default 0 check (tx_count >= 0),
  utxo_count integer not null default 0 check (utxo_count >= 0),
  oldest_utxo_days integer,
  source text,
  first_checked_at timestamptz not null default now(),
  last_checked_at timestamptz not null default now(),
  check_count bigint not null default 1 check (check_count >= 1)
);

create index if not exists btc_address_index_last_checked_idx on public.btc_address_index (last_checked_at desc);
create index if not exists btc_address_index_last_activity_idx on public.btc_address_index (last_activity);
create index if not exists btc_address_index_balance_idx on public.btc_address_index (balance_sats desc);

create table if not exists public.btc_address_occurrences (
  id bigint generated by default as identity primary key,
  address text not null references public.btc_address_index(address) on delete cascade,
  source_type text not null check (source_type in ('search','saved_search','inspector','watchlist')),
  source_ref text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique(address, source_type, source_ref)
);

create index if not exists btc_address_occurrences_address_idx on public.btc_address_occurrences (address, last_seen_at desc);
create index if not exists btc_address_occurrences_source_idx on public.btc_address_occurrences (source_type, source_ref);

create table if not exists public.btc_research_notes (
  address text primary key references public.btc_address_index(address) on delete cascade,
  title text not null default '',
  notes text not null default '',
  tags text[] not null default '{}'::text[],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.btc_address_index enable row level security;
alter table public.btc_address_occurrences enable row level security;
alter table public.btc_research_notes enable row level security;
revoke all on table public.btc_address_index from anon, authenticated;
revoke all on table public.btc_address_occurrences from anon, authenticated;
revoke all on table public.btc_research_notes from anon, authenticated;
grant all on table public.btc_address_index to service_role;
grant all on table public.btc_address_occurrences to service_role;
grant all on table public.btc_research_notes to service_role;
grant usage, select on sequence public.btc_address_occurrences_id_seq to service_role;
