-- Phase 1: admin-controlled users, ownership and activity tracking
create extension if not exists pgcrypto;

create table if not exists public.app_users (
  id uuid primary key default gen_random_uuid(),
  username text not null,
  display_name text not null default '',
  password_salt text not null,
  password_hash text not null,
  role text not null default 'user' check (role in ('admin','user')),
  active boolean not null default true,
  session_version integer not null default 1 check (session_version >= 1),
  created_by uuid references public.app_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz
);
create unique index if not exists app_users_username_lower_idx on public.app_users (lower(username));
create index if not exists app_users_role_active_idx on public.app_users (role,active);

create table if not exists public.user_activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.app_users(id) on delete set null,
  username_snapshot text not null default '',
  action text not null,
  tool text not null default '',
  entity_type text not null default '',
  entity_id text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists user_activity_logs_user_time_idx on public.user_activity_logs (user_id,created_at desc);
create index if not exists user_activity_logs_action_time_idx on public.user_activity_logs (action,created_at desc);

create table if not exists public.user_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.app_users(id) on delete cascade,
  kind text not null default 'info',
  title text not null,
  message text not null default '',
  entity_type text not null default '',
  entity_id text not null default '',
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists user_notifications_user_time_idx on public.user_notifications (user_id,created_at desc);

-- Attribute persistent work to users. Existing records remain unowned and are visible to admins only.
alter table if exists public.btc_background_jobs add column if not exists user_id uuid references public.app_users(id) on delete set null;
alter table if exists public.evm_background_jobs add column if not exists user_id uuid references public.app_users(id) on delete set null;
alter table if exists public.btc_saved_searches add column if not exists user_id uuid references public.app_users(id) on delete set null;
alter table if exists public.btc_watchlist add column if not exists user_id uuid references public.app_users(id) on delete set null;
alter table if exists public.btc_research_notes add column if not exists user_id uuid references public.app_users(id) on delete set null;

create index if not exists btc_background_jobs_user_idx on public.btc_background_jobs (user_id,created_at desc);
create index if not exists evm_background_jobs_user_idx on public.evm_background_jobs (user_id,created_at desc);

alter table public.app_users enable row level security;
alter table public.user_activity_logs enable row level security;
alter table public.user_notifications enable row level security;
revoke all on table public.app_users from anon, authenticated;
revoke all on table public.user_activity_logs from anon, authenticated;
revoke all on table public.user_notifications from anon, authenticated;
grant all on table public.app_users to service_role;
grant all on table public.user_activity_logs to service_role;
grant all on table public.user_notifications to service_role;
grant usage, select on sequence public.user_activity_logs_id_seq to service_role;
grant usage, select on sequence public.user_notifications_id_seq to service_role;
