-- Phase 1 hardening: allow separate users to research/watch the same public BTC address.

-- The original research-notes table used address as its primary key in the single-user build.
alter table public.btc_research_notes
  add column if not exists id bigint generated by default as identity;

alter table public.btc_research_notes
  drop constraint if exists btc_research_notes_pkey;

alter table public.btc_research_notes
  add constraint btc_research_notes_pkey primary key (id);

create unique index if not exists btc_research_notes_user_address_idx
  on public.btc_research_notes (user_id, address)
  where user_id is not null;

-- Remove the old single-user unique(address) constraint from watchlist, whatever its generated name was.
do $$
declare
  constraint_name text;
begin
  select c.conname
    into constraint_name
  from pg_constraint c
  where c.conrelid = 'public.btc_watchlist'::regclass
    and c.contype = 'u'
    and pg_get_constraintdef(c.oid) ilike '%(address)%'
  limit 1;

  if constraint_name is not null then
    execute format('alter table public.btc_watchlist drop constraint %I', constraint_name);
  end if;
end $$;

create unique index if not exists btc_watchlist_user_address_idx
  on public.btc_watchlist (user_id, address)
  where user_id is not null;

grant usage, select on sequence public.btc_research_notes_id_seq to service_role;
