'use strict';
(()=>{
  const $=s=>document.querySelector(s),form=$('#ap-form'),address=$('#ap-address'),msg=$('#ap-message'),results=$('#ap-results'),body=$('#ap-body'),metrics=$('#ap-metrics');const EVM=/^0x[a-fA-F0-9]{40}$/;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const short=v=>v&&v.length>18?`${v.slice(0,8)}…${v.slice(-6)}`:v||'—';const metric=(k,v)=>`<article class="metric-card"><p>${esc(k)}</p><strong>${esc(v)}</strong></article>`;
  function show(text,ok=false){msg.textContent=text;msg.className=`message${ok?' success':''}`;msg.hidden=false}function stateBadge(s){const map={active:'#b9f8ce',revoked:'#9ba7bf',unknown:'#ffe29a'};return`<strong style="color:${map[s]||'#fff'}">${esc(s||'unknown')}</strong>`}
  async function req(payload){const r=await fetch('/api/evm-approvals',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}
  function value(e){if(e.kind==='operator')return e.currentValue===true?'Approved':'Not approved';if(e.kind==='erc721_token')return e.currentValue?short(String(e.currentValue)):'—';if(e.currentValue==null)return'—';const n=String(e.currentValue);return n.length>24?`${n.slice(0,12)}…${n.slice(-8)} raw`:n+' raw'}
  form.addEventListener('submit',async ev=>{ev.preventDefault();const a=address.value.trim();if(!EVM.test(a))return show('Enter a valid public EVM address.');results.hidden=true;show('Scanning public approval events and validating current state…');try{const d=await req({address:a,lookbackBlocks:Number($('#ap-lookback').value)});const s=d.summary||{};metrics.innerHTML=[['Approval records',Number(s.events||0).toLocaleString()],['Active',Number(s.active||0).toLocaleString()],['Revoked',Number(s.revoked||0).toLocaleString()],['Unknown',Number(s.unknown||0).toLocaleString()],['Very large allowances',Number(s.veryLargeAllowances||0).toLocaleString()],['Active operators',Number(s.operatorApprovals||0).toLocaleString()]].map(x=>metric(...x)).join('');body.innerHTML=(d.events||[]).map(e=>`<tr><td>${esc(e.networkLabel)}</td><td>${esc(e.label)}</td><td class="mono" title="${esc(e.contract)}">${esc(short(e.contract))}</td><td class="mono" title="${esc(e.spender)}">${esc(short(e.spender))}${e.tokenId?`<div class="field-help">token #${esc(e.tokenId)}</div>`:''}</td><td>${stateBadge(e.state)}</td><td>${esc(value(e))}</td><td>${esc(String(e.risk||'unknown').replaceAll('_',' '))}</td><td>${e.transactionHash?`<a target="_blank" rel="noopener noreferrer" href="${esc(e.explorer)}">View tx</a>`:'—'}</td></tr>`).join('')||'<tr><td colspan="8">No approval events were found in the selected historical window.</td></tr>';$('#ap-checked').textContent=`${Number(d.lookbackBlocks||0).toLocaleString()} blocks`;results.hidden=false;show(`Approval research complete · ${s.active||0} active · ${s.revoked||0} revoked · ${s.unknown||0} unknown.`,true);results.scrollIntoView({behavior:'smooth',block:'start'})}catch(e){show(e.message)}});
  $('#ap-clear').onclick=()=>{address.value='';results.hidden=true;msg.hidden=true;address.focus()};const q=new URLSearchParams(location.search).get('address');if(q){address.value=q;setTimeout(()=>form.requestSubmit(),80)}
})();
