'use strict';
(()=>{
  const pages=Array.isArray(window.__SITE_PAGES__)?window.__SITE_PAGES__:[];
  const fallback=[{href:'/',label:'Research Dashboard',file:'dashboard.html'},{href:'/evm',label:'EVM Recovery & Address Auditor',file:'index.html'},{href:'/btc',label:'BTC Discovery Lab',file:'btc-discovery.html'},{href:'/address-workspace.html',label:'Cross-chain Address Workspace',file:'address-workspace.html'},{href:'/jobs.html',label:'Background Job Manager',file:'jobs.html'},{href:'/notifications.html',label:'Notifications Center',file:'notifications.html'},{href:'/exports.html',label:'Export Center',file:'exports.html'},{href:'/approvals.html',label:'EVM Approval Research',file:'approvals.html'},{href:'/recover',label:'Seed-word Recovery Assistant',file:'recovery-assistant.html'},{href:'/admin.html',label:'Admin Control Center',file:'admin.html'}];
  const items=(pages.length?pages:fallback).filter(x=>x&&x.href&&x.label);
  const current=location.pathname.replace(/\/$/,'')||'/';
  const normalize=href=>{try{return new URL(href,location.origin).pathname.replace(/\/$/,'')||'/'}catch{return href}};
  const active=href=>normalize(href)===current||(current==='/btc-discovery.html'&&normalize(href)==='/btc')||(current==='/recovery-assistant.html'&&normalize(href)==='/recover')||(current==='/index.html'&&normalize(href)==='/evm');
  const iconFor=(label,file)=>{const t=`${label} ${file}`.toLowerCase();if(t.includes('dashboard'))return'⌂';if(t.includes('private')||t.includes('login'))return'⌾';if(t.includes('btc')||t.includes('bitcoin'))return'₿';if(t.includes('recover'))return'↺';if(t.includes('approval'))return'✓';if(t.includes('notification'))return'◉';if(t.includes('export'))return'⇩';if(t.includes('job'))return'⟳';if(t.includes('wallet'))return'◇';if(t.includes('address'))return'⌁';if(t.includes('research'))return'◫';if(t.includes('admin'))return'⚙';return'Ξ'};
  const descFor=(label,file)=>{const t=`${label} ${file}`.toLowerCase();if(t.includes('dashboard'))return'Unified research command center';if(t.includes('private')||t.includes('login'))return'Protected deployment access';if(t.includes('approval'))return'Read-only EVM approval research';if(t.includes('notification'))return'Background and watchlist alerts';if(t.includes('export'))return'Download research data';if(t.includes('job'))return'BTC and EVM persistent work';if(t.includes('btc')||t.includes('bitcoin'))return'Bitcoin public-data research';if(t.includes('recover'))return'Owner-authorized recovery tools';if(t.includes('address'))return'Cross-chain public address analysis';if(t.includes('admin'))return'Users, access and work tracking';return'Crypto research tool'};
  const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  const brandStyle=document.createElement('style');brandStyle.textContent='.crypto-brand-logo{width:36px;height:36px;border-radius:50%;object-fit:cover;background:#fff;box-shadow:0 0 0 1px rgba(255,255,255,.16),0 0 26px rgba(111,134,255,.2)}.crypto-intro-logo{width:clamp(96px,14vw,160px);height:clamp(96px,14vw,160px);border-radius:50%;object-fit:cover;background:#fff;margin:0 auto 20px;box-shadow:0 0 0 1px rgba(255,255,255,.18),0 0 70px rgba(111,134,255,.25);opacity:0;animation:x-rise .8s .05s forwards}.crypto-sound-note{display:block;margin-top:10px;color:#667493;font-size:.68rem;letter-spacing:.08em;text-transform:uppercase}';document.head.append(brandStyle);

  const header=document.createElement('header');header.className='crypto-global-nav';header.innerHTML=`<div class="crypto-nav-inner"><a class="crypto-brand" href="/" aria-label="CHAIN//LAB home"><img class="crypto-brand-logo" src="/anonymous-logo.svg" alt=""><span class="crypto-brand-copy">CHAIN//LAB<small>public crypto intelligence</small></span></a><nav class="crypto-desktop-links" aria-label="Primary navigation"></nav><div class="crypto-nav-actions"><button class="crypto-tools-button" type="button" aria-expanded="false">All tools <span aria-hidden="true">⌄</span></button><button class="crypto-mobile-toggle" type="button" aria-label="Open navigation" aria-expanded="false"><span></span></button></div></div><div class="crypto-tools-menu" role="menu"></div>`;document.body.prepend(header);
  const desktop=header.querySelector('.crypto-desktop-links');for(const item of items.slice(0,5)){const a=document.createElement('a');a.className=`crypto-nav-link${active(item.href)?' active':''}`;a.href=item.href;a.textContent=item.shortLabel||item.label;desktop.append(a)}
  const menu=header.querySelector('.crypto-tools-menu');menu.innerHTML=items.map(item=>`<a role="menuitem" class="crypto-menu-item${active(item.href)?' active':''}" href="${item.href}"><span class="crypto-menu-icon">${iconFor(item.label,item.file)}</span><span class="crypto-menu-copy"><strong>${escapeHtml(item.label)}</strong><small>${escapeHtml(descFor(item.label,item.file))}</small></span></a>`).join('');
  const drawer=document.createElement('div');drawer.className='crypto-mobile-drawer';drawer.innerHTML=`<div class="crypto-mobile-backdrop"></div><aside class="crypto-mobile-sheet" aria-label="Mobile navigation"><div class="crypto-mobile-section-title">All crypto tools</div>${items.map(item=>`<a class="crypto-mobile-link${active(item.href)?' active':''}" href="${item.href}"><span class="crypto-menu-icon">${iconFor(item.label,item.file)}</span><span>${escapeHtml(item.label)}</span></a>`).join('')}</aside>`;document.body.append(drawer);
  const toolsBtn=header.querySelector('.crypto-tools-button'),mobileBtn=header.querySelector('.crypto-mobile-toggle');const closeAll=()=>{menu.classList.remove('open');drawer.classList.remove('open');toolsBtn?.setAttribute('aria-expanded','false');mobileBtn?.setAttribute('aria-expanded','false');document.body.style.overflow=''};toolsBtn?.addEventListener('click',()=>{const open=!menu.classList.contains('open');closeAll();if(open){menu.classList.add('open');toolsBtn.setAttribute('aria-expanded','true')}});mobileBtn?.addEventListener('click',()=>{const open=!drawer.classList.contains('open');closeAll();if(open){drawer.classList.add('open');mobileBtn.setAttribute('aria-expanded','true');document.body.style.overflow='hidden'}});drawer.querySelector('.crypto-mobile-backdrop')?.addEventListener('click',closeAll);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAll()});document.addEventListener('click',e=>{if(menu.classList.contains('open')&&!header.contains(e.target))closeAll()});
  const hero=document.querySelector('.hero');if(hero&&!hero.querySelector('.crypto-page-chip')){const chip=document.createElement('div');chip.className='crypto-page-chip';chip.textContent='Encrypted public-data workspace';hero.querySelector('div:last-child')?.prepend(chip)}

  function playEntrySound(){try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const ctx=new AC(),master=ctx.createGain();master.gain.setValueAtTime(.0001,ctx.currentTime);master.gain.exponentialRampToValueAtTime(.2,ctx.currentTime+.04);master.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+1.45);master.connect(ctx.destination);const low=ctx.createOscillator(),lowGain=ctx.createGain();low.type='sine';low.frequency.setValueAtTime(48,ctx.currentTime);low.frequency.exponentialRampToValueAtTime(112,ctx.currentTime+1.1);lowGain.gain.setValueAtTime(.18,ctx.currentTime);lowGain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+1.35);low.connect(lowGain).connect(master);low.start();low.stop(ctx.currentTime+1.4);for(const [delay,freq] of [[.08,880],[.24,1320],[.41,1760],[.68,990]]){const o=ctx.createOscillator(),g=ctx.createGain();o.type='triangle';o.frequency.setValueAtTime(freq,ctx.currentTime+delay);o.frequency.exponentialRampToValueAtTime(freq*1.7,ctx.currentTime+delay+.12);g.gain.setValueAtTime(.0001,ctx.currentTime+delay);g.gain.exponentialRampToValueAtTime(.1,ctx.currentTime+delay+.015);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+delay+.18);o.connect(g).connect(master);o.start(ctx.currentTime+delay);o.stop(ctx.currentTime+delay+.2)}const buffer=ctx.createBuffer(1,ctx.sampleRate*.9,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);const noise=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),ng=ctx.createGain();noise.buffer=buffer;filter.type='highpass';filter.frequency.value=2800;ng.gain.value=.035;noise.connect(filter).connect(ng).connect(master);noise.start(ctx.currentTime+.05);setTimeout(()=>ctx.close().catch(()=>{}),1800)}catch{}}

  if(sessionStorage.getItem('crypto-intro-seen')!=='1'){
    const intro=document.createElement('div');intro.className='crypto-intro';intro.setAttribute('role','dialog');intro.setAttribute('aria-label','Welcome');intro.innerHTML=`<div class="crypto-intro-grid"></div><div class="crypto-intro-glow"></div><div class="crypto-intro-content"><img class="crypto-intro-logo" src="/anonymous-logo.svg" alt="CHAIN//LAB"><div class="crypto-intro-kicker">CHAIN//LAB · 2026</div><h1>Step into the anonymous world</h1><p>Research smarter. Move through crypto with clarity.</p><button type="button" class="crypto-enter">Enter the network</button><span class="crypto-sound-note">Original cyber entry sound plays on enter</span></div>`;document.body.append(intro);const dismiss=()=>{if(intro.classList.contains('hidden'))return;sessionStorage.setItem('crypto-intro-seen','1');intro.classList.add('hidden');setTimeout(()=>intro.remove(),800)};intro.querySelector('.crypto-enter')?.addEventListener('click',()=>{playEntrySound();setTimeout(dismiss,260)});setTimeout(dismiss,6500)
  }
})();
