'use strict';
(()=>{
  const $=s=>document.querySelector(s),body=$('#jobs-body'),status=$('#jobs-status');let jobs=[];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const dt=v=>v?new Date(v).toLocaleString():'—';
  async function json(url,opt={}){const r=await fetch(url,{credentials:'same-origin',...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}
  function controls(j){const a=[];if(['running','queued'].includes(j.status))a.push(`<button class="secondary small-button" data-act="pause" data-id="${j.id}" data-kind="${j.kind}">Pause</button>`);if(['paused','waiting_provider','error'].includes(j.status))a.push(`<button class="primary small-button" data-act="resume" data-id="${j.id}" data-kind="${j.kind}">Resume</button>`);if(!['complete','target_reached','cancelled'].includes(j.status))a.push(`<button class="secondary small-button" data-act="cancel" data-id="${j.id}" data-kind="${j.kind}">Cancel</button>`);a.push(`<button class="secondary small-button" data-act="view" data-id="${j.id}" data-kind="${j.kind}">View</button>`);a.push(`<button class="secondary small-button" data-act="delete" data-id="${j.id}" data-kind="${j.kind}">Delete</button>`);return a.join(' ')}
  function render(){const chain=$('#jobs-chain').value,st=$('#jobs-status-filter').value,q=$('#jobs-search').value.trim().toLowerCase();const filtered=jobs.filter(j=>(chain==='all'||j.kind===chain)&&(st==='all'||j.status===st)&&(!q||`${j.name} ${j.owner?.username||''} ${j.owner?.display_name||''}`.toLowerCase().includes(q)));body.innerHTML=filtered.length?filtered.map(j=>{const total=Number(j.total||0),checked=Number(j.checked_count||0),pct=total?Math.min(100,checked/total*100):0;return`<tr><td><strong>${esc(j.name||'Untitled job')}</strong><div class="field-help">${new Date(j.created_at).toLocaleString()}</div></td><td>${j.chain}</td><td>${esc(j.owner?.display_name||j.owner?.username||'Unowned')}</td><td>${esc(String(j.status||'').replaceAll('_',' '))}</td><td><progress max="100" value="${pct}" style="width:130px"></progress><div class="field-help">${checked.toLocaleString()} / ${total.toLocaleString()}</div></td><td>${Number(j.matches||0).toLocaleString()}</td><td>${dt(j.last_heartbeat_at||j.updated_at)}</td><td>${controls(j)}</td></tr>`}).join(''):'<tr><td colspan="8">No jobs match these filters.</td></tr>';status.textContent=`${filtered.length} shown · ${jobs.length} total`}
  async function load(){try{const d=await json('/api/jobs');jobs=d.jobs||[];render()}catch(e){status.textContent=e.message}}
  async function act(kind,action,id){if(action==='view'){location.href=kind==='btc'?'/btc#btc-background-scanner':'/evm';return}if(action==='delete'&&!confirm('Delete this job record?'))return;const endpoint=kind==='btc'?'/api/btc-background-jobs':'/api/evm-background-jobs';if(action==='delete')await json(`${endpoint}?id=${encodeURIComponent(id)}`,{method:'DELETE'});else await json(endpoint,{method:'POST',body:JSON.stringify({action,id})});await load()}
  body.addEventListener('click',e=>{const b=e.target.closest('button[data-act]');if(!b)return;act(b.dataset.kind,b.dataset.act,b.dataset.id).catch(err=>status.textContent=err.message)});
  for(const id of['jobs-chain','jobs-status-filter','jobs-search'])$('#'+id).addEventListener('input',render);$('#jobs-refresh').onclick=load;load();setInterval(load,10000);
})();
