'use strict';
(()=>{
  const style=document.createElement('style');style.textContent='.crypto-user-box{display:flex;align-items:center;gap:7px;padding:5px 7px;border:1px solid rgba(151,167,255,.14);border-radius:12px;background:rgba(255,255,255,.025)}.crypto-user-name{font-size:.78rem;font-weight:850;color:#eef1ff;max-width:130px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.crypto-user-role{font-size:.62rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase;color:#8fa0cb}.crypto-user-admin,.crypto-user-logout,.crypto-user-notif{font-size:.72rem;font-weight:850;color:#cbd2ff;text-decoration:none;background:transparent;border:0;padding:5px 6px;cursor:pointer;position:relative}.crypto-user-notif-badge{position:absolute;top:-4px;right:-4px;min-width:17px;height:17px;padding:0 4px;border-radius:999px;display:grid;place-items:center;background:#ff5d8f;color:white;font-size:.57rem;font-weight:900;box-shadow:0 0 18px rgba(255,93,143,.35)}@media(max-width:980px){.crypto-user-name,.crypto-user-role,.crypto-user-admin{display:none}.crypto-user-box{padding:3px}.crypto-user-logout{min-height:36px}}';document.head.append(style);
  const post=(action,tool='navigation',metadata={})=>fetch('/api/activity',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({action,tool,metadata})}).catch(()=>{});
  async function unread(){try{const r=await fetch('/api/notifications',{credentials:'same-origin',cache:'no-store'});if(!r.ok)return 0;const d=await r.json();return Number(d.unread||0)}catch{return 0}}
  async function init(){try{const r=await fetch('/api/me',{credentials:'same-origin',cache:'no-store'});if(!r.ok)return;const d=await r.json(),u=d.user;if(!u)return;if(u.role!=='admin')document.querySelectorAll('a[href="/admin.html"]').forEach(x=>x.remove());const actions=document.querySelector('.crypto-nav-actions');if(actions){const n=await unread();const box=document.createElement('div');box.className='crypto-user-box';box.innerHTML=`<span class="crypto-user-name">${escapeHtml(u.displayName||u.username)}</span><span class="crypto-user-role">${escapeHtml(u.role)}</span><a class="crypto-user-notif" href="/notifications.html" aria-label="Notifications">◉${n?`<span class="crypto-user-notif-badge">${n>99?'99+':n}</span>`:''}</a>${u.role==='admin'?'<a class="crypto-user-admin" href="/admin.html">Admin</a>':''}<button class="crypto-user-logout" type="button">Log out</button>`;actions.prepend(box);box.querySelector('.crypto-user-logout').onclick=async()=>{await post('logout','auth');await fetch('/api/login',{method:'DELETE',credentials:'same-origin'}).catch(()=>{});location.replace('/login.html')}}post('page_view','navigation',{path:location.pathname,title:document.title});document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;const text=(b.textContent||'').trim().slice(0,80);if(!text||/password|seed|phrase|private key/i.test(text))return;post('ui_click','navigation',{label:text,path:location.pathname})},{passive:true})}catch{}}
  function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))}
  init();
})();
