import crypto from 'node:crypto';

export const COOKIE_NAME='chainlab_session';
export const SESSION_MAX_AGE=60*60*12;

export function normalizeSecret(value){let s=String(value??'').trim();if(s.length>=2&&((s[0]==='"'&&s.at(-1)==='"')||(s[0]==="'"&&s.at(-1)==="'")))s=s.slice(1,-1).trim();return s}
export function sessionSecret(){return normalizeSecret(process.env.AUTH_SESSION_SECRET)||normalizeSecret(process.env.SITE_PASSWORD)||normalizeSecret(process.env.WALLET_TOOL_PASSWORD)||normalizeSecret(process.env.APP_ACCESS_TOKEN)}
export function supabaseConfig(){try{const u=new URL(process.env.SUPABASE_URL?.trim());let p=u.pathname.replace(/\/+$/,'');if(!p||p==='/')p='/rest/v1';else if(!p.endsWith('/rest/v1'))p+='/rest/v1';u.pathname=p;u.search='';u.hash='';const key=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_KEY;return key?{url:u.toString().replace(/\/$/,''),key}:null}catch{return null}}
export async function sb(c,path,opt={}){const r=await fetch(`${c.url}/${path}`,{...opt,headers:{apikey:c.key,Authorization:`Bearer ${c.key}`,'Content-Type':'application/json',Accept:'application/json',...(opt.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{}if(!r.ok)throw new Error(d?.message||d?.hint||d?.code||`Supabase ${r.status}`);return d}
export function safeEqual(a,b){const x=Buffer.from(String(a??'')),y=Buffer.from(String(b??''));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
export function hashPassword(password,salt=crypto.randomBytes(18).toString('base64url')){const hash=crypto.scryptSync(String(password),salt,64,{N:16384,r:8,p:1}).toString('base64url');return{salt,hash}}
export function verifyPassword(password,salt,hash){try{return safeEqual(hashPassword(password,salt).hash,hash)}catch{return false}}
function b64(value){return Buffer.from(JSON.stringify(value)).toString('base64url')}
function sign(text){const secret=sessionSecret();if(!secret)throw new Error('AUTH_SESSION_SECRET or a fallback website secret is not configured.');return crypto.createHmac('sha256',secret).update(text).digest('base64url')}
export function createSessionCookie(user){const payload={uid:user.id,username:user.username,role:user.role,sv:Number(user.session_version||1),exp:Math.floor(Date.now()/1000)+SESSION_MAX_AGE};const body=b64(payload),token=`${body}.${sign(body)}`;return `${COOKIE_NAME}=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${SESSION_MAX_AGE}`}
export function clearSessionCookie(){return `${COOKIE_NAME}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`}
function cookieValue(req,name){const header=req.headers?.get?req.headers.get('cookie'):req.headers?.cookie;for(const part of String(header||'').split(';')){const [k,...rest]=part.trim().split('=');if(k===name)return rest.join('=')}return''}
export function decodeSession(req){const token=cookieValue(req,COOKIE_NAME);const dot=token.lastIndexOf('.');if(dot<1)return null;const body=token.slice(0,dot),sig=token.slice(dot+1);if(!safeEqual(sign(body),sig))return null;try{const p=JSON.parse(Buffer.from(body,'base64url').toString('utf8'));if(!p?.uid||Number(p.exp)<=Math.floor(Date.now()/1000))return null;return p}catch{return null}}
export async function requireUser(req,{admin=false}={}){const p=decodeSession(req);if(!p)throw Object.assign(new Error('Authentication required.'),{status:401});const c=supabaseConfig();if(!c)throw Object.assign(new Error('Supabase is not configured.'),{status:503});const rows=await sb(c,`app_users?select=id,username,display_name,role,active,session_version,last_login_at&id=eq.${encodeURIComponent(p.uid)}&limit=1`);const u=rows?.[0];if(!u||!u.active||Number(u.session_version)!==Number(p.sv))throw Object.assign(new Error('Session expired or account disabled.'),{status:401});if(admin&&u.role!=='admin')throw Object.assign(new Error('Administrator access required.'),{status:403});return{...u,c}}
export async function logActivity(c,user,action,{tool='',entityType='',entityId='',metadata={}}={}){const safeMeta={};for(const[k,v]of Object.entries(metadata||{})){if(/seed|phrase|private|password|token|secret/i.test(k))continue;safeMeta[k]=typeof v==='string'?v.slice(0,300):v}await sb(c,'user_activity_logs',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({user_id:user?.id||null,username_snapshot:user?.username||'',action:String(action).slice(0,120),tool:String(tool).slice(0,120),entity_type:String(entityType).slice(0,80),entity_id:String(entityId).slice(0,160),metadata:safeMeta})})}
export function json(res,status,payload,headers={}){if(typeof res?.status==='function'){for(const[k,v]of Object.entries({'Cache-Control':'no-store,max-age=0','Content-Type':'application/json; charset=utf-8',...headers}))res.setHeader(k,v);return res.status(status).json(payload)}return Response.json(payload,{status,headers:{'Cache-Control':'no-store,max-age=0',...headers}})}
