import crypto from 'node:crypto';

const BTC=/^(?:[13][a-km-zA-HJ-NP-Z1-9]{25,34}|bc1[ac-hj-np-z02-9]{11,71})$/i;
function send(r,s,p){r.setHeader('Cache-Control','no-store,max-age=0');r.setHeader('Content-Type','application/json; charset=utf-8');return r.status(s).json(p)}
function eq(a,b){if(typeof a!=='string'||typeof b!=='string')return false;const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function cfg(){try{const u=new URL(process.env.SUPABASE_URL?.trim());let p=u.pathname.replace(/\/+$/,'');if(!p||p==='/')p='/rest/v1';else if(!p.endsWith('/rest/v1'))p+='/rest/v1';u.pathname=p;u.search='';u.hash='';const key=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_KEY;return key?{url:u.toString().replace(/\/$/,''),key}:null}catch{return null}}
async function sb(c,path,opt={}){const r=await fetch(`${c.url}/${path}`,{...opt,headers:{apikey:c.key,Authorization:`Bearer ${c.key}`,'Content-Type':'application/json',Accept:'application/json',...(opt.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{}if(!r.ok)throw new Error(d?.message||d?.hint||d?.code||`Supabase ${r.status}`);return d}
function typeOf(a){if(/^1/.test(a))return'p2pkh';if(/^3/.test(a))return'p2sh';if(/^bc1p/i.test(a))return'taproot';if(/^bc1q/i.test(a))return'bech32';return'unknown'}
function inFilter(values){return encodeURIComponent(`in.(${values.map(v=>`"${String(v).replaceAll('"','')}"`).join(',')})`)}
function num(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d}
function iso(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString()}
async function readMeta(c,addresses){if(!addresses.length)return[];const idx=await sb(c,`btc_address_index?select=*&address=${inFilter(addresses)}`);const occ=await sb(c,`btc_address_occurrences?select=address,source_type,source_ref,last_seen_at&address=${inFilter(addresses)}&order=last_seen_at.desc&limit=1000`);let wl=[];try{wl=await sb(c,`btc_watchlist?select=address&id=not.is.null&address=${inFilter(addresses)}`)}catch{}const w=new Set((wl||[]).map(x=>x.address));const om=new Map();for(const row of occ||[]){const a=row.address;if(!om.has(a))om.set(a,[]);om.get(a).push(row)}return addresses.map(a=>{const x=(idx||[]).find(r=>r.address===a)||null;const o=om.get(a)||[];return{address:a,index:x,previouslyChecked:Boolean(x),lastChecked:x?.last_checked_at||null,checkCount:Number(x?.check_count||0),occurrenceCount:o.length,sourceTypes:[...new Set(o.map(v=>v.source_type))],recentOccurrences:o.slice(0,12),watchlisted:w.has(a)}})}
async function upsert(c,records,sourceType,sourceRef,metadata={}){const now=new Date().toISOString();const addresses=[...new Set(records.map(x=>String(x.address||'').trim()).filter(a=>BTC.test(a)))].slice(0,100);if(!addresses.length)return[];const existing=await sb(c,`btc_address_index?select=*&address=${inFilter(addresses)}`);const em=new Map((existing||[]).map(x=>[x.address,x]));const rows=records.filter(x=>addresses.includes(String(x.address||'').trim())).map(x=>{const address=String(x.address).trim(),old=em.get(address);return{address,address_type:x.addressType||x.address_type||old?.address_type||typeOf(address),first_seen:iso(x.firstSeen||x.first_seen)||old?.first_seen||null,last_activity:iso(x.lastActivity||x.last_activity)||old?.last_activity||null,balance_sats:String(Math.max(0,num(x.balanceSats??x.balance_sats,old?.balance_sats||0))),funded_sats:String(Math.max(0,num(x.fundedSats??x.funded_sats,old?.funded_sats||0))),spent_sats:String(Math.max(0,num(x.spentSats??x.spent_sats,old?.spent_sats||0))),tx_count:Math.max(0,Math.trunc(num(x.txCount??x.tx_count,old?.tx_count||0))),utxo_count:Math.max(0,Math.trunc(num(x.utxoCount??x.utxo_count,old?.utxo_count||0))),oldest_utxo_days:x.oldestUtxoDays??x.oldest_utxo_days??old?.oldest_utxo_days??null,source:x.source||old?.source||sourceType,first_checked_at:old?.first_checked_at||now,last_checked_at:iso(x.checkedAt||x.last_checked_at)||now,check_count:Number(old?.check_count||0)+1}});await sb(c,'btc_address_index?on_conflict=address',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(rows)});if(['search','saved_search','inspector','watchlist'].includes(sourceType)){const occ=addresses.map(address=>({address,source_type:sourceType,source_ref:String(sourceRef||'').slice(0,180),metadata:metadata&&typeof metadata==='object'?metadata:{},last_seen_at:now}));await sb(c,'btc_address_occurrences?on_conflict=address,source_type,source_ref',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(occ)})}return readMeta(c,addresses)}
export default async function handler(req,res){const expected=process.env.APP_ACCESS_TOKEN;if(expected&&!eq(req.headers['x-app-access-token'],expected))return send(res,401,{error:'Incorrect or missing app passcode.'});const c=cfg();if(!c)return send(res,503,{error:'Supabase is not configured.'});try{if(req.method==='GET'){const raw=String(req.query?.addresses||req.query?.address||'');const addresses=raw.split(',').map(x=>x.trim()).filter(a=>BTC.test(a)).slice(0,100);return send(res,200,{items:await readMeta(c,addresses)})}if(req.method==='POST'){const b=req.body||{};const records=Array.isArray(b.records)?b.records:Array.isArray(b.addresses)?b.addresses.map(address=>({address})):[b];const sourceType=['search','saved_search','inspector','watchlist'].includes(b.sourceType)?b.sourceType:'search';const items=await upsert(c,records,sourceType,b.sourceRef,b.metadata);return send(res,200,{items})}res.setHeader('Allow','GET, POST');return send(res,405,{error:'Method not allowed.'})}catch(e){return send(res,502,{error:e.message||'Address index request failed. Run supabase/003_btc_address_index.sql if the index tables are not installed yet.'})}}