import { authorizeSessionOrApp } from './_auth.mjs';
function send(res,status,payload){res.setHeader('Cache-Control','no-store,max-age=0');res.setHeader('Content-Type','application/json; charset=utf-8');return res.status(status).json(payload)}
function safeEqual(a,b){if(typeof a!=='string'||typeof b!=='string')return false;const x=Buffer.from(a),y=Buffer.from(b);if(x.length!==y.length)return false;return crypto.timingSafeEqual(x,y)}
import crypto from 'node:crypto';
const BTC_RE=/^(?:[13][a-km-zA-HJ-NP-Z1-9]{25,34}|bc1[ac-hj-np-z02-9]{11,71})$/i;
function typeOf(a){if(/^1/.test(a))return 'Legacy P2PKH';if(/^3/.test(a))return 'P2SH / wrapped SegWit';if(/^bc1p/i.test(a))return 'Taproot';if(/^bc1q/i.test(a))return 'Native SegWit';return 'Unknown'}
async function fetchTimeout(url,ms=15000){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{headers:{Accept:'application/json'},signal:c.signal})}finally{clearTimeout(t)}}
async function json(url){let last;for(let i=0;i<3;i++){try{const r=await fetchTimeout(url);if(r.ok)return await r.json();last=new Error(`HTTP ${r.status}`);if(r.status!==429&&r.status<500)throw last}catch(e){last=e}if(i<2)await new Promise(r=>setTimeout(r,700*(2**i)))}throw last||new Error('Public Bitcoin API failed')}
async function inspect(base,address){const e=encodeURIComponent(address);const [s,txs,u]=await Promise.all([json(`${base}/address/${e}`),json(`${base}/address/${e}/txs`),json(`${base}/address/${e}/utxo`)]);const c=s?.chain_stats||{};const confirmed=(Array.isArray(txs)?txs:[]).filter(x=>x?.status?.confirmed&&x.status.block_time).sort((a,b)=>Number(b.status.block_time)-Number(a.status.block_time));const toIso=x=>x?new Date(Number(x)*1000).toISOString():null;const now=Date.now();const utxos=(Array.isArray(u)?u:[]).map(x=>{const ts=x?.status?.confirmed&&x.status.block_time?toIso(x.status.block_time):null;return{txid:x.txid,vout:x.vout,valueSats:Number(x.value||0),timestamp:ts,ageDays:ts?Math.max(0,Math.floor((now-Date.parse(ts))/86400000)):null}}).sort((a,b)=>(b.ageDays??-1)-(a.ageDays??-1));const timeline=confirmed.slice(0,25).map(tx=>({txid:tx.txid,timestamp:toIso(tx.status.block_time),blockHeight:tx.status.block_height||null,feeSats:Number(tx.fee||0)}));return{address,addressType:typeOf(address),balanceSats:Math.max(0,Number(c.funded_txo_sum||0)-Number(c.spent_txo_sum||0)),fundedSats:Number(c.funded_txo_sum||0),spentSats:Number(c.spent_txo_sum||0),txCount:Number(c.tx_count||0),lastActivity:toIso(confirmed[0]?.status?.block_time),firstActivity:toIso(confirmed.at(-1)?.status?.block_time),utxoCount:utxos.length,oldestUtxoDays:utxos.find(x=>x.ageDays!==null)?.ageDays??null,utxos:utxos.slice(0,50),timeline,source:base.includes('mempool')?'mempool.space':'blockstream.info',checkedAt:new Date().toISOString()}}
export default async function handler(req,res){if(req.method!=='POST'){res.setHeader('Allow','POST');return send(res,405,{error:'Method not allowed.'})}const expected=process.env.APP_ACCESS_TOKEN;if(expected&&!safeEqual(req.headers['x-app-access-token'],expected))return send(res,401,{error:'Incorrect or missing app passcode.'});const address=String(req.body?.address||'').trim();if(!BTC_RE.test(address))return send(res,400,{error:'Enter a valid Bitcoin Mainnet address.'});for(const base of ['https://mempool.space/api','https://blockstream.info/api']){try{return send(res,200,await inspect(base,address))}catch{}}return send(res,502,{error:'Public Bitcoin providers are temporarily unavailable.'})}
